title: 'National Library Board - Guide to NLB Mobile app'
description: 'Find out how the NLB Mobile app can be your personal library to let you read and learn anytime, anywhere. Get help on using NLB Mobile.'
url: 'https://mobileapp.nlb.gov.sg'
google_analytics: null
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
resources_name: spotlight
paginate_path: '/spotlight/page:num'
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    get-started-with:
        output: true
    toptips:
        output: true
favicon: /images/favicon-nlb.ico
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
